### ISSUE TITLE
Tree profile generation changed from 1.7.10. Intended?

### ISSUE THREAD

**Issue by jdratlif** [LexManos/YUNoMakeGoodMap#26]
I played with this mod in Sky Factory 2.5, and I'm trying it in a custom pack now with 1.10. In 1.7.10, the TREE profile put the grass block at y level 64 and grew the tree above it. In the 1.10 version, the top leaf block is at y level 64, so your platform is actually much lower than "sea level".

Is this an intended change?

I know you can add custom profiles, but I don't really understand how to do that. Do you have to make a custom NBT file? Suggestions on how to go about that? (MCEdit?) I don't really understand NBT.

Thanks.

**Comment by LexManos** [comment]
Yes actually, I never liked playing where the default platform would change the sky color when you were just jumping around. So it got raised up a bit. Plus there was an issue with sea level not being correctly calculated so meh. This is intended. 

You make a assets/{modid}/structures/SkyBlockPlatforms.txt
Each line with the name of a nbt file.
The NBT is just a structure file exported using the vanilla Structure block.
Only special thing is if there is a Structure data block with the data SPAWN_POINT then it'll shift the structure so that the spawn is at that block.
