### ISSUE TITLE
No block generation

### ISSUE THREAD

**Issue by Natey214** [LexManos/YUNoMakeGoodMap#37]
I am looking for a way make it so it does not make a block, I know custom structures can be made but have found no guides or ways to do so. Didn't know where else to post this.

**Comment by LexManos** [comment]
By default it'll spawn 1 block of grass if it doesn't have anything else.
You COULD create a custom platform with literally nothing in it. That should work for what you want.
However, I'd advise against it as the player would most likely fall through the world and die due to loading.
This mod doesn't give any flight abilities.

**Comment by Natey214** [comment]
I am looking for some instruction on HOW to make a custom structure.

**Comment by LexManos** [comment]
http://minecraft.gamepedia.com/Structure_Block

**Comment by Natey214** [comment]
Thank you, I had no idea this block even existed. I'm making a sky block and they cannot start with any dirt which is why I needed the custom structure.
